# Ansible inventory for k3s cluster
# Auto-generated by Terraform

[server]
%{~ for name in server_names }
${name} ansible_host=${server_ips[name]}
%{~ endfor }

[agent]
%{~ for name in agent_names }
${name} ansible_host=${agent_ips[name]}
%{~ endfor }

[k3s_cluster:children]
server
agent

[all:vars]
ansible_user=${vm_user}
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
