# Ansible inventory for k3s cluster
# Auto-generated by Terraform

[k3s_masters]
%{~ for name in server_names }
${name} ansible_host=${server_ips[name]}
%{~ endfor }

[k3s_agents]
%{~ for name in agent_names }
${name} ansible_host=${agent_ips[name]}
%{~ endfor }

[k3s_cluster:children]
k3s_masters
k3s_agents

[all:vars]
ansible_user=${vm_user}
ansible_ssh_private_key_file=../terraform/proxmox/${replace(ssh_key_path, ".pub", "")}
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
